media: media
content:
  - name: Pins
    label: Pins
    type: collection
    path: 'content/pins'
    filename: "{{slug}}.md"
    view:
      fields: [ title, published, date ]
    fields:
      - name: isPublished
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: slug
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text